Adapt to upcoming changes in HA Core 2022.3
fondberg/spotcast pull request #299
Opened 2022-02-14 12:49 UTC by emontnemery

The native Spotify integration has seen some changes which will be included in HA Core 2022.3

This PR adapts to those changes, while being backwards compatible

Relevant HA Core PRs:
- https://github.com/home-assistant/core/pull/66285
- https://github.com/home-assistant/core/pull/66314

2022-02-14 13:19 UTC, emontnemery commented
Not sure if backwards compatibility is wanted, or if the minimum version `hacs.json` should be bumped instead?

2022-02-21 12:51 UTC, fcusson commented
Sorry about the delay, I was fairly swamped in the last few weeks. I'll start to review the code during the week. I will check if we can make the project work without requiring a version bump. If not possible, we'll simply bump it.

2022-02-25 01:31 UTC, fcusson commented
@hmmbob can you provide more details on what's breaking?

2022-02-25 05:58 UTC, hmmbob commented
The exact things Erik mentions:

> The breaking changes are exactly what's in this PR:
> 
> * `SpotifyMediaPlayer._devices` is renamed to `SpotifyMediaPlayer.entity.data.devices.data`
> * `SpotifyMediaPlayer._spotify` is renamed to `SpotifyMediaPlayer.data.client`
> 
> The PR now checks for `_devices` / `_ spotify`, and falls back to `.data.xxx` If there's no need to be backwards compatible, we should bump the HA Core version in `hacs,json` to `2022.3.0` and just access the `.data.xxx`

2022-02-25 06:03 UTC, hmmbob commented
The fix works, running it locally on 2022.3.0b1 and issue is solved.

2022-02-25 12:45 UTC, fcusson commented
@hmmbob thank you for the details. I'm working on a potential way to have retrocompatibility while using the new method. If it's not possible, we will simply bump the home assistant version to 2022.3 like @emontnemery mentionned

2022-02-25 13:17 UTC, fcusson commented
@emontnemery after testing, we have no breaking changes with your method. Code is working in 2022.2. Actually the if _devices logic you included isn't necessary even. For retrocompatibility, especially if we have a user with a very old version that doesn't have access to the new method you access, we'll keep error handling. I'll send a code review, there is a few changes I would like to see first.

2022-02-25 13:31 UTC, fcusson requested changes

2022-02-25 13:31 UTC, fcusson commented on custom_components/spotcast/helpers.py
> +                if hasattr(entity, "_devices"):
modify to a try/except. The error type is `AttributeError`. I was thinking of something like that:

```python
try:
    devices_data = entity._devices
except(AttributeError):
    devices_data = entity.data.devices.data

_LOGGER.debug(f"get_spotify_devices: {entity.entity_id}: {entity.name}: %s", devices_data)
```

2022-02-25 13:31 UTC, fcusson commented on custom_components/spotcast/helpers.py
> +        if hasattr(entity, "_spotify"):
encapsulate in a try/except also

```Python
try:
    resp = spotify_media_player._spotify.devices()
except(AttributeError):
    resp = spotify_media_player.data.client.devices()
```

2022-02-27 14:42 UTC, fcusson commented
Due to the near approaching date for the 2022.03, I'll merge the request and make the change directly.

2022-02-27 14:42 UTC, fcusson approved these changes

2022-02-27 14:42 UTC, merged